; -- zeropage definitions --------------------
; note: TOTALLY stomps all over Applesoft/Integer BASIC, do not use together!

; arguments for subroutines
arg1	:= $60
arg2	:= $61
arg3	:= $62
arg4	:= $63
arg5	:= $64
arg6	:= $65

arg1w	:= $66
arg2w	:= $68
arg3w	:= $6A
arg4w	:= $6C
arg5w	:= $6E

; for use in subroutines
temp1	:= $70
temp2	:= $71
temp3	:= $72
temp4	:= $73
temp5	:= $74
temp6	:= $75

temp1w	:= $76
temp2w	:= $78
temp3w	:= $7A
temp4w	:= $7C
temp5w	:= $7E
		
; intended for variables in main program
var1	:= $80
var2	:= $81
var3	:= $82
var4	:= $83
var5	:= $84
var6	:= $85

var1w	:= $86
var2w	:= $88
var3w	:= $8A
var4w	:= $8C
var5w	:= $8E
	
